// <auto-generated />
using Dotnet9.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnet9.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260222061546_StudentCourseToDB")]
    partial class StudentCourseToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerMall", b =>
                {
                    b.Property<int>("CustomersId")
                        .HasColumnType("int");

                    b.Property<int>("MallsId")
                        .HasColumnType("int");

                    b.HasKey("CustomersId", "MallsId");

                    b.HasIndex("MallsId");

                    b.ToTable("MallCustomers", (string)null);
                });

            modelBuilder.Entity("CustomerShop", b =>
                {
                    b.Property<int>("CustomersId")
                        .HasColumnType("int");

                    b.Property<int>("ShopsId")
                        .HasColumnType("int");

                    b.HasKey("CustomersId", "ShopsId");

                    b.HasIndex("ShopsId");

                    b.ToTable("CustomerShops", (string)null);
                });

            modelBuilder.Entity("Dotnet9.Models.Courses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mathematics",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physics",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chemistry",
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("Dotnet9.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Dotnet9.Models.CustomerMalls", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("MallId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "MallId");

                    b.HasIndex("MallId");

                    b.ToTable("CustomerMalls");
                });

            modelBuilder.Entity("Dotnet9.Models.Mall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Floors")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Malls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Floors = 5,
                            Location = "Downtown",
                            Name = "Sunshine Mall"
                        },
                        new
                        {
                            Id = 2,
                            Floors = 3,
                            Location = "Riverside",
                            Name = "Riverfront Mall"
                        },
                        new
                        {
                            Id = 3,
                            Floors = 4,
                            Location = "Hillside",
                            Name = "Mountainview Mall"
                        });
                });

            modelBuilder.Entity("Dotnet9.Models.MallOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MallId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MallId")
                        .IsUnique();

                    b.ToTable("MallOwners");
                });

            modelBuilder.Entity("Dotnet9.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MallId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MallId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("Dotnet9.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Charlie"
                        });
                });

            modelBuilder.Entity("CustomerMall", b =>
                {
                    b.HasOne("Dotnet9.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dotnet9.Models.Mall", null)
                        .WithMany()
                        .HasForeignKey("MallsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerShop", b =>
                {
                    b.HasOne("Dotnet9.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dotnet9.Models.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dotnet9.Models.Courses", b =>
                {
                    b.HasOne("Dotnet9.Models.Student", "Student")
                        .WithMany("courses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Dotnet9.Models.CustomerMalls", b =>
                {
                    b.HasOne("Dotnet9.Models.Customer", "Customer")
                        .WithMany("CustomerMalls")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dotnet9.Models.Mall", "Mall")
                        .WithMany("CustomerMalls")
                        .HasForeignKey("MallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Mall");
                });

            modelBuilder.Entity("Dotnet9.Models.MallOwner", b =>
                {
                    b.HasOne("Dotnet9.Models.Mall", "Mall")
                        .WithOne("MallOwner")
                        .HasForeignKey("Dotnet9.Models.MallOwner", "MallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mall");
                });

            modelBuilder.Entity("Dotnet9.Models.Shop", b =>
                {
                    b.HasOne("Dotnet9.Models.Mall", "Mall")
                        .WithMany("Shops")
                        .HasForeignKey("MallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mall");
                });

            modelBuilder.Entity("Dotnet9.Models.Customer", b =>
                {
                    b.Navigation("CustomerMalls");
                });

            modelBuilder.Entity("Dotnet9.Models.Mall", b =>
                {
                    b.Navigation("CustomerMalls");

                    b.Navigation("MallOwner");

                    b.Navigation("Shops");
                });

            modelBuilder.Entity("Dotnet9.Models.Student", b =>
                {
                    b.Navigation("courses");
                });
#pragma warning restore 612, 618
        }
    }
}
